import { SearchSelectOption } from '../../../../shared/components/serach-select/models/search-select.model';

export const AVAILABLE_CURRENCIES = [
  {
    id: 'usdt',
    label: 'Tether',
    value: 'USDT',
    networks: ['ERC-20', 'BEP-20', 'TRC-20'],
    color: '#26A17B',
    minDepositAmount: 10,
    minWithdrawAmount: 10,
    maxWithdrawAmount: 50000,
  },
  {
    id: 'usdc',
    label: 'USD Coin',
    value: 'USDC',
    networks: ['ERC-20'],
    color: '#2775CA',
    minDepositAmount: 10,
    minWithdrawAmount: 10,
    maxWithdrawAmount: 50000,
  },
  {
    id: 'dai',
    label: 'Dai',
    value: 'DAI',
    networks: ['ERC-20'],
    color: '#F5AC37',
    minDepositAmount: 10,
    minWithdrawAmount: 10,
    maxWithdrawAmount: 50000,
  },
  {
    id: 'busd',
    label: 'Binance USD',
    value: 'BUSD',
    networks: ['ERC-20'],
    color: '#F0B90B',
    minDepositAmount: 10,
    minWithdrawAmount: 10,
    maxWithdrawAmount: 50000,
  },
  {
    id: 'eth',
    label: 'Ethereum',
    value: 'ETH',
    networks: ['ERC-20'],
    color: '#627EEA',
    minDepositAmount: 0.01,
    minWithdrawAmount: 0.01,
    maxWithdrawAmount: 1000,
  },
  {
    id: 'bnb',
    label: 'BNB',
    value: 'BNB',
    networks: ['ERC-20', 'BEP-20'],
    color: '#F3BA2F',
    minDepositAmount: 0.05,
    minWithdrawAmount: 0.05,
    maxWithdrawAmount: 10000,
  },
  {
    id: 'shib',
    label: 'Shiba Inu',
    value: 'SHIBA',
    networks: ['ERC-20'],
    color: '#F0431A',
    minDepositAmount: 100000,
    minWithdrawAmount: 100000,
    maxWithdrawAmount: 1000000000,
  },
  {
    id: 'btc',
    label: 'Bitcoin',
    value: 'BTC',
    networks: ['BTC'],
    color: '#F7931A',
    minDepositAmount: 0.0001,
    minWithdrawAmount: 0.0001,
    maxWithdrawAmount: 100,
  },
  {
    id: 'ltc',
    label: 'Litecoin',
    value: 'LTC',
    networks: ['LTC'],
    color: '#345D9D',
    minDepositAmount: 0.01,
    minWithdrawAmount: 0.01,
    maxWithdrawAmount: 10000,
  },
  {
    id: 'trx',
    label: 'TRON',
    value: 'TRX',
    networks: ['TRX'],
    color: '#EB0029',
    minDepositAmount: 10,
    minWithdrawAmount: 10,
    maxWithdrawAmount: 1000000,
  },
];
